name: Build Bear Audio Limiter

on:
  push:
    branches: [ "windows-master" ]
  pull_request:
    branches: [ "windows-master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pycaw comtypes Pillow pystray pywin32

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconsole --onefile --add-data "Bear_logo.png;." --add-data "icon.png;." --icon=icon.png Bear.pyw

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Bear-Build-Windows
        path: |
          dist/Bear.exe
          Install_Bear.bat
